name: build.yml

on: 
  push:
  branches: [master]

env:
  AZURE_WEBAPP_NAME: 'SICI'
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '8.0.x'

jobs:
  build: 
    name: Construye la aplicación
    runs-on: ubuntu-latest
    steps:
      - name: Recupera el codigo fuente
        uses: actions/checkout@v4
      - name: Instalar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - name: Instala las dependencias del proyecto
        run: dotnet restore

      - name: publica la aplicación
        run: dotnet publish --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'






